# Generated by Django 5.2 on 2025-04-11 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('adress', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('wsite', models.URLField()),
                ('wtel', models.URLField(blank=True, null=True)),
                ('wvk', models.URLField(blank=True, null=True)),
                ('winsta', models.URLField(blank=True, null=True)),
                ('wface', models.URLField(blank=True, null=True)),
                ('wtwit', models.URLField(blank=True, null=True)),
                ('wtic', models.URLField(blank=True, null=True)),
                ('wother', models.URLField(blank=True, null=True)),
                ('icon', models.ImageField(upload_to='est/')),
                ('prev', models.ImageField(blank=True, upload_to='est/')),
                ('promo_medio', models.URLField(blank=True)),
                ('coords', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='shop.establishment')),
            ],
        ),
    ]
