# Generated by Django 5.2 on 2025-06-28 20:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=100)),
                ('описание', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=100)),
                ('страна', models.CharField(max_length=100)),
                ('описание', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_id', models.IntegerField(unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Квалификация',
                'verbose_name_plural': 'Квалификации',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('дата_создания', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('пользователь', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='корзина', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'db_table': 'shop_cart',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=200)),
                ('описание', models.TextField()),
                ('фото_товара', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('цена', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('количество_на_складе', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('категория', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('производитель', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.manufacturer')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('количество', models.PositiveIntegerField(verbose_name='Количество')),
                ('добавлен', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('корзина', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='элементы', to='shop.cart', verbose_name='Корзина')),
                ('товар', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Элемент корзины',
                'verbose_name_plural': 'Элементы корзины',
                'unique_together': {('корзина', 'товар')},
            },
        ),
    ]
