# Generated by Django 5.2 on 2025-06-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_recreate_main_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualification',
            options={'verbose_name': 'Квалификация', 'verbose_name_plural': 'Квалификации'},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='создана',
            new_name='дата_создания',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='обновлена',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='добавлен',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='qualification_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table=None,
        ),
    ]
